kernel:
    resource: ../../src/Kernel.php
    type: annotation

controllers:
    resource: ../../src/Customer/Adapter/Framework/Http/Controller/
    type: annotation
    prefix: /api/customers
    trailing_slash_on_root: false